### ISSUE TITLE
Add JSON API backend to station ob history

### ISSUE THREAD

**Issue by akrherz** [akrherz/iem#120]
Currently, the `/sites/obhistory.php` has too much business logic and is not accessible.  Let us have a JSON emitting backend for it and then folks can consume it as well.

**Comment by akrherz** [comment]
- [ ] Requested addition of a CSV format output for this web service

**Comment by grguthrie** [comment]
ANy chance that this is still an open request? Wither JSON or XML output from station history?

**Comment by akrherz** [comment]
@grguthrie I don't understand your question.  Yes, this issue is still Open, what makes you question it?

**Comment by grguthrie** [comment]
Thanks – I just wondered if I had missed any changes or progress.

---------------------------------------------------------------
|      Dr. Gregory Guthrie                                      |
---------------------------------------------------------------

**Comment by akrherz** [comment]
This is now tracked by akrherz/iem-web-services#9
