### ISSUE TITLE
Where does the data come from for IEM?

### ISSUE THREAD

**Issue by sckott** [akrherz/iem#207]
Sorry to ask such a broad question, but in an R package i maintain we're trying not to duplicate efforts of another R package that is in fact a client for IEM ->  https://github.com/ropensci/rnoaa/issues/280 

From what I understand IEM uses NOAA ASOS data https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/automated-surface-observing-system-asos - is that right? If so, all or some of it?

**Comment by akrherz** [comment]
No worries on reaching out here.  For my real-time data, I am processing `METAR` format products provided by the US National Weather Service's satellite feed called noaaport.  This format is generally used for the observations coming from ASOS-type platforms.   For archive backfilling, I look at the [NCEI ISD](https://www.ncdc.noaa.gov/isd).  Please chime back in here if you have further questions.

**Comment by sckott** [comment]
thanks very much - no further questions at this time
