### ISSUE TITLE
Understanding the Metar.py package better to help in a senior thesis

### ISSUE THREAD

**Issue by LawrsB** [akrherz/iem#251]
Good evening,

My name is Lawrence Blundo. I am a senior meteorology student at Embry-Riddle Aeronautical University. I am currently working on a senior thesis, and one of my tasks is to read through ten-years of METAR data from Boston, KBOS and find the reports where the 3/6 hourly temperature, 6 hourly precipitation, 24 hour temperature, and 24 hour precipitation. I'm going a little stir crazy as I've been sitting here trying to figure out how the Metar.py package exactly works (I know I can use it to help out with my project but I just can't figure out how it works). I would just like to know how the package scans through a METAR report and decodes it into a report that is readable and easy to understand. If someone could help me out I would be grateful. I want to code the program that will scan the data myself, but I just would like know how the Metar.py package does it first before I tackle with creating a code on my own.
[BOS.txt](https://github.com/akrherz/iem/files/4271106/BOS.txt)

The data I'm working with will be attatched to this message. You don't need to read all of it, but you can see why I'm having issues pulling out the data I need. If you are curious about what my thesis is, then you can send me an email at LawsBlundo22@outlook.com

**Comment by akrherz** [comment]
Spamming this message over various github projects is of very bad taste.

**Comment by LawrsB** [comment]
Hi Daryl,

I apologize if my message on three different projects appeared as spam. I had signed up for an account with GitHub today, and I wasn’t completely sure what the best way to contact akrhez/iem was, so I had sent the message on three different projects in the hopes that he would see one of them. Again, I apologize that they were spammed, but I really do need his help and if there is another source that is better for contacting him for help with my question then I would be grateful.

Have a wonderful weekend!

Best Regards,

Lawrence Blundo

**Comment by akrherz** [comment]
This isn't hard, visit the website and click on the [contact us](https://mesonet.agron.iastate.edu/info/contacts.php) link.
