### ISSUE TITLE
Legend goes missing on ISUSM autoplot when variables missing

### ISSUE THREAD

**Issue by hluker** [akrherz/iem#259]
(legend) https://mesonet.agron.iastate.edu/agclimate/smts.php?station=BOOI4&opt=1&year1=2020&month1=9&day1=6&hour1=0&year2=2020&month2=9&day2=10&hour2=11

(no legend) https://mesonet.agron.iastate.edu/agclimate/smts.php?station=CNAI4&opt=1&year1=2020&month1=9&day1=6&hour1=0&year2=2020&month2=9&day2=10&hour2=11

For the 3-panel ISUSM plot, the legend for the top two panels seems to vanish if a variable goes missing (in Castana's case, the 50 inch observation)

**Comment by akrherz** [comment]
Thanks, should be corrected now.
