### ISSUE TITLE
Enhance NWS VTEC Download page

### ISSUE THREAD

**Issue by akrherz** [akrherz/iem#47]
Currently, the VTEC download page only offers per WFO selection and does not include all attributes that may be desired.  The feature request includes:
- Search by state
- Search by VTEC phenomena + significance combination
- Include HVTEC attribute in the download

**Comment by mbalonso** [comment]
Open to any help w/this?

**Comment by akrherz** [comment]
@mbalonso Oh certainly, but I am unsure if anybody can make sense of my junky code that makes this happen.  I can barely remember how things work myself :(

**Comment by mbalonso** [comment]
Looks good to me :)  Only thing I was not sure of was whether or not you had the actual records for the mesosite.stations table you reference in the [NetworkTable class](https://github.com/akrherz/iem/blob/master/include/network.php).  I dug around but could not find anything other the the sql for the base structure.

**Comment by akrherz** [comment]
@mbalonso I am unsure what you mean by actual records.  I can dump something out if helpful....

**Comment by mbalonso** [comment]
@akrherz Sorry for the delay, things got a little crazy over here.  I just wasn't sure if you had a dump of all the records/rows in mesosite.stations.  Just wanted to make sure I am working as closely w/the prod setup as possible so you don't need to go back and fix anything I screw up :)

**Comment by akrherz** [comment]
@mbalonso Can you help me understanding what interaction you are hoping the VTEC page has with the mesosite.stations table?  Perhaps I could just do a database dump of it?  Would that suffice?

**Comment by mbalonso** [comment]
@akrherz a db dump would be great.  Sorry for the confusion.

**Comment by akrherz** [comment]
[stations.db.gz](https://github.com/akrherz/iem/files/397018/stations.db.gz)

created with `pg_dump -a -t stations mesosite > stations.db`

**Comment by mbalonso** [comment]
Thank you @akrherz

**Comment by mbalonso** [comment]
Sorry for the radio silence.  I've been wanting to revamp my dev environment and have been battling Windows 10 and docker for almost 2 weeks.

**Comment by mbalonso** [comment]
@akrherz Do you have some script (e.g. composer, etc.) that generates the vendor dir under htdocs or am I missing something?

**Comment by akrherz** [comment]
@mbalonso I have a seperate git repo for it https://github.com/akrherz/vendor

**Comment by mbalonso** [comment]
@akrherz doh, missed that.  Thanks!

**Comment by mbalonso** [comment]
@akrherz Sorry for all the chatter.  2 questions:

1) Do you have a preference for whether any dynamic dropdowns query a page to retrieve the states for a given country or would you rather the full country/state lookup be downloaded to the client on the initial page load and any changes are handled client-side?

2) Is there a reason you were using Zend JSON (e.g. servers are running php < 5.2.0) or can json_encode/json_decode be used?

**Comment by akrherz** [comment]
No worries.

1) country? You mean county?  Currently, I have a page that does this dynamically:
http://mesonet.agron.iastate.edu/vtec/search.php#byugc

2) yes, this code was written way back in the day.  Good point that I could remove this dependency now.

**Comment by mbalonso** [comment]
Omg.  Somehow wires in my brain got totally crossed - my brain was in metar mode at the time I guess - and I was thinking I was working on http://mesonet.agron.iastate.edu/request/download.phtml.  Wow.

So to clarify, you want to add the state search feature to http://mesonet.agron.iastate.edu/vtec/ ?

**Comment by akrherz** [comment]
I think the featured requested are for this page:
http://mesonet.agron.iastate.edu/request/gis/watchwarn.phtml

**Comment by mbalonso** [comment]
I tried to commit some changes but it looks like I do not have access to create a new branch. Would you prefer I just fork it and you can look at the changes there?

Hope you are enjoying your weekend!

**Comment by akrherz** [comment]
@mbalonso , typically the workflow is to fork the upstream repo, create a feature branch from your forked repo, commit the changes to that branch and then use the github UI to submit the pull request to the upstream repo.  Thanks for your efforts on this.

**Comment by mbalonso** [comment]
Ahh crap, sorry about that @akrherz.  I'll get that setup.  Thanks for the patience!

**Comment by mbalonso** [comment]
@akrherz pardon my postgres ineptitude, I only use mysql.  Everything looks correct but w/out a table full of vtecs, I am just looking at the resulting sql, so it is hard to tell for sure.

**Comment by mbalonso** [comment]
Sorry for all the chatter on this.

My solution for #79 was to search mesosite.stations by state abbrev and pull a distinct list of WFO's which was then fed into the original WFO search code already in place.  However, this seems to be resulting in some unexpected behavior.  

`select distinct wfo from stations where state in ('PA')`

returns: LWX, PHI, CTP, PBZ, OKX, BGM.  Most of those are expected but I was surprised to see LWX and OKX but the stations table does indeed have stations in PA mapped to those WFOs.  Is this ok?  If not, is there a table that has a list of all the WFO's - I could not find one?  

Sorry, I feel like I have created more work w/this than I hoped to prevent.

**Comment by akrherz** [comment]
Will look more later, but the warnings table has a `ugc` column, which is the six char UGC code for each VTEC product.  You can filter like so `substr(ugc, 1, 2) = 'PA'`

**Comment by mbalonso** [comment]
Sorry for disappearing on this - things got pretty crazy here.

Would it be possible to get a partial dump of the WW table so that I can test this against real data?

**Comment by akrherz** [comment]
Hi @mbalonso , I thought we got this work merged and done with?  What's left to do?

**Comment by mbalonso** [comment]
It did work except for the issue I pointed out in https://github.com/akrherz/iem/issues/47#issuecomment-255536635:

> My solution for #79 was to search mesosite.stations by state abbrev and pull a distinct list of WFO's which was then fed into the original WFO search code already in place. However, this seems to be resulting in some unexpected behavior.
> 
> select distinct wfo from stations where state in ('PA')
> 
> returns: LWX, PHI, CTP, PBZ, OKX, BGM. Most of those are expected but I was surprised to see LWX and OKX but the stations table does indeed have stations in PA mapped to those WFOs. Is this ok? If not, is there a table that has a list of all the WFO's - I could not find one?

If that is ok, we can certainly leave it as is.  Your call.

**Comment by akrherz** [comment]
@mbalonso I thought I addressed that in a [later commit](https://github.com/akrherz/iem/commit/864c08ecde6524b60590cc72b71e152c6f74e794#diff-db0475c3b304ab6d602767be08b8228d), is it not working on the website?

**Comment by mbalonso** [comment]
Crap, I swear I responded to this last week.  Anyway, I just brought it up b/c I didn't know you accounted for this in a separate commit.  Nicely done!

**Comment by akrherz** [comment]
Closing as work on this is completed.  Can open new issues for any further requests/bugs.
