### ISSUE TITLE
Question about downloading APSIM met file

### ISSUE THREAD

**Issue by wxystudio** [akrherz/iem#693]
Hello, now I try to download the APSIM met file from the IEM website. After I set all the options and click the "process data request", a new webpage will  pop out like this:

<img width="300" alt="image" src="https://github.com/akrherz/iem/assets/17384283/1c3f8000-7611-4726-8c01-fb20d8d2819d">

And I can manually save it as '.met' file.

But actually there are 3 options to view this file:

<img width="100" alt="image" src="https://github.com/akrherz/iem/assets/17384283/59960ba0-158f-431e-aa63-23fef7fac216">

I find these 3 options will lead to the same result, which is "view online", no download. How can I download it as Excel, or automatically download it to disk? 

Thanks

**Comment by akrherz** [comment]
Thank you, this sounds like a bug, will investigate it.
