### ISSUE TITLE
How to understand information from complex table heads？

### ISSUE THREAD

**Issue by forestbat** [akrherz/iem#941]
This is a station which code is CA_DCP_AMBC1, and its table head is this:
```
station    utc_valid    PCIRRZZ    PPBRZZ    PPDRZZ    PPDRZZZ    PPHRZZ    PPKRZZ    PPQRZZ    PPQRZZZ    PPTRZZ    SDIRRZZ    SFVRRZZ    TAIRRZZ    VBIRRZZ
```
Several fields all have PP suchs PPQRZZ, so is it precipitation or river discharge? I don't understand from https://www.weather.gov/media/mdl/SHEF_CodeManual_5July2012.pdf, if you can awnser me, I will be deeply grateful.

**Comment by akrherz** [comment]
:wave: @forestbat , the `PP` code is listed on that PDF in Appendix G.  It is precipitation.

**Comment by akrherz** [comment]
The third character `Q` needs to be looked up within table 3.  Welcome to the horrors of SHEF.

**Comment by forestbat** [comment]
> The third character `Q` needs to be looked up within table 3. Welcome to the horrors of SHEF.

Yes I know `Q` means discharge, what I mean is: why will `Q` appear after `PP`? It's precipitation, or discharge caused by precipitation?

**Comment by akrherz** [comment]
> Yes I know `Q` means discharge

Show me that is what `Q` says in Table 3.

**Comment by forestbat** [comment]
![图片](https://github.com/user-attachments/assets/5d5c795b-fec1-4291-9204-5bff42f78a5c)
Sorry I made a mistake.
